language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
  
install:
  - /home/travis/.phpenv/versions/5.4/bin/composer self-update
  - composer update --prefer-dist
  
services:
  - mysql
  
test:
  adapter: mysql2
  database: db_name
  username: root
  encoding: utf8

before_install:
  - mysql -e "create database IF NOT EXISTS db_name;" -uroot
  
before_script:
  - mysql -e 'create database db_name;'
  
script:
  - ./vendor/bin/phpunit
  
after_script:
  - ./vendor/bin/test-reporter
  
env:
  global:
    secure: XnXSc7nxJMIrm/EJ1KuwlN4f+sj2R/sR0IFHdOdbOfMKyZ/u6WEgZ3vNrdeAsisiC/QUJJ00DGku1pAl3t3Hzvam0N/SiHtXjB1ZLVbX00S1PEZ6Z+h9zoaUBXWoN6+0OdKN0Xjmj2lwvTpvUxUZXNabilOw0F9WS/+JasofqBQ=

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache