language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
  
install:
  - composer update --prefer-dist
  
services:
  - mysql
  
test:
  adapter: mysql2
  database: db_name
  username: root
  encoding: utf8

before_script:
  - mysql -e 'create database db_name;'